"""Scanner tuning bridge — reads/writes tuning_config.json.

The EOD agent writes a tuning config after each session.
The scanner reads it before every scan to adapt behavior:
- exclude stale symbols the LLM already rejected
- tighten/loosen thresholds based on regime and performance
- adjust risk limits based on trailing performance

The config is never edited by agents — only generated by the proven
`generate_tuning_config` MCP tool (called by EOD). Human can override
any field by editing the JSON directly.
"""

import json
import os
from pathlib import Path
from datetime import datetime, timezone


TUNING_CONFIG_PATH = Path(__file__).resolve().parent / "tuning_config.json"

# Default config (zero overrides — scanner uses SOP defaults)
DEFAULT_TUNING = {
    "version": "",
    "generated_by": "",
    "generated_at": "",
    "exclude_symbols": [],
    "exclude_reason": {},
    "threshold_overrides": {},
    "risk_limit_overrides": {},
    "strategy_blacklist": [],
    "notes": "",
}


def load_tuning_config() -> dict:
    """Load the current tuning config. Returns DEFAULT if file missing/corrupt."""
    try:
        if TUNING_CONFIG_PATH.exists():
            cfg = json.loads(TUNING_CONFIG_PATH.read_text())
            # Merge with defaults so new keys are always present
            merged = {**DEFAULT_TUNING, **cfg}
            return merged
    except (json.JSONDecodeError, OSError) as e:
        pass
    return {**DEFAULT_TUNING}


def save_tuning_config(cfg: dict) -> None:
    """Save tuning config to disk."""
    TUNING_CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
    TUNING_CONFIG_PATH.write_text(json.dumps(cfg, indent=2, default=str))


def get_tuning_config() -> dict:
    """Public API — returns the current tuning config for the scanner."""
    return load_tuning_config()


def apply_tuning(swing_config: dict) -> dict:
    """Apply tuning overrides to the SWING_V1 configuration dict.

    Returns a new dict with threshold_overrides merged in.
    Does not modify the original SWING_V1.
    """
    tuning = load_tuning_config()
    overrides = tuning.get("threshold_overrides", {})
    merged = {**swing_config}
    # Only apply overrides that exist as keys in SWING_V1
    for key, value in overrides.items():
        if key in merged:
            merged[key] = value
    return merged


def is_symbol_excluded(symbol: str) -> tuple[bool, str]:
    """Check if a symbol is in the exclusion list. Returns (excluded, reason)."""
    tuning = load_tuning_config()
    if symbol in tuning.get("exclude_symbols", []):
        reason = tuning.get("exclude_reason", {}).get(symbol, "excluded by tuning config")
        return True, reason
    return False, ""


def get_risk_limit_overrides() -> dict:
    """Return any risk limit overrides from the tuning config."""
    tuning = load_tuning_config()
    return tuning.get("risk_limit_overrides", {})


def generate_tuning_config(
    exclude_symbols: list[str] | None = None,
    exclude_reasons: dict[str, str] | None = None,
    threshold_overrides: dict | None = None,
    risk_limit_overrides: dict | None = None,
    strategy_blacklist: list[str] | None = None,
    notes: str = "",
    generated_by: str = "eod-review",
) -> dict:
    """Generate a new tuning config for the scanner.

    Called by the EOD agent via MCP tool. Merges with existing config
    so that fields not provided are preserved.

    Returns the saved config.
    """
    existing = load_tuning_config()

    # Build new config
    new_cfg = {**DEFAULT_TUNING}
    new_cfg["version"] = datetime.now(timezone.utc).isoformat()
    new_cfg["generated_by"] = generated_by
    new_cfg["generated_at"] = datetime.now(timezone.utc).isoformat()

    # Merge provided overrides (explicit null clears the field)
    if exclude_symbols is not None:
        new_cfg["exclude_symbols"] = exclude_symbols
    else:
        new_cfg["exclude_symbols"] = existing.get("exclude_symbols", [])

    if exclude_reasons is not None:
        new_cfg["exclude_reason"] = exclude_reasons
    else:
        new_cfg["exclude_reason"] = existing.get("exclude_reason", {})

    if threshold_overrides is not None:
        # Validate — only allow keys that exist in SWING_V1
        valid_keys = {
            "min_dollar_vol20", "price_min", "price_max",
            "m_atr_pct_min", "m_atr_pct_max", "m_rs10_min",
            "m_roc50_min", "m_chase_atr_mult",
            "m_pullback_rsi3_max", "m_pullback_atr_dist",
            "r_atr_pct_min", "r_drop3_min", "r_rsi3_max",
        }
        validated = {k: v for k, v in threshold_overrides.items() if k in valid_keys}
        new_cfg["threshold_overrides"] = validated
    else:
        new_cfg["threshold_overrides"] = existing.get("threshold_overrides", {})

    if risk_limit_overrides is not None:
        new_cfg["risk_limit_overrides"] = risk_limit_overrides
    else:
        new_cfg["risk_limit_overrides"] = existing.get("risk_limit_overrides", {})

    if strategy_blacklist is not None:
        new_cfg["strategy_blacklist"] = strategy_blacklist
    else:
        new_cfg["strategy_blacklist"] = existing.get("strategy_blacklist", [])

    new_cfg["notes"] = notes if notes else existing.get("notes", "")

    save_tuning_config(new_cfg)
    return new_cfg


def reset_tuning_config() -> dict:
    """Reset tuning config to defaults (no overrides)."""
    cfg = {**DEFAULT_TUNING}
    save_tuning_config(cfg)
    return cfg
